"""Publication-quality figure builders for MedKnow.

All figures are plain matplotlib (no 3D, no clutter), 300 DPI, and can be
regenerated by ``scripts/medknow_make_figures.py``.
"""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
from sklearn.metrics import precision_recall_curve, roc_curve

from medknow.visualization.styles import COHORT_LABELS, COLORS

COHORT_COLORS = {
    "internal_test": COLORS["internal"],
    "rsna": COLORS["rsna"],
    "nih": COLORS["nih"],
}



def fig_roc(ax, labels, p_pos, cohort: str, auc_text: str) -> None:
    """ROC curve for one cohort."""
    labels = np.asarray(labels)
    p_pos = np.asarray(p_pos)
    if len(np.unique(labels)) < 2:
        return
    fpr, tpr, _ = roc_curve(labels, p_pos)
    ax.plot(fpr, tpr, lw=2, color=COHORT_COLORS[cohort],
            label=f"{COHORT_LABELS[cohort]} (AUC {auc_text})")
    ax.plot([0, 1], [0, 1], "--", color="gray", lw=1)
    ax.set_xlabel("False positive rate")
    ax.set_ylabel("True positive rate")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)


def fig_pr(ax, labels, p_pos, cohort: str, auprc_text: str) -> None:
    """Precision-recall curve for one cohort."""
    labels = np.asarray(labels)
    p_pos = np.asarray(p_pos)
    if len(np.unique(labels)) < 2:
        return
    precision, recall, _ = precision_recall_curve(labels, p_pos)
    ax.plot(recall, precision, lw=2, color=COHORT_COLORS[cohort],
            label=f"{COHORT_LABELS[cohort]} (AUPRC {auprc_text})")
    ax.set_xlabel("Recall (sensitivity)")
    ax.set_ylabel("Precision")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)


def fig_calibration(
    ax,
    p_pos,
    labels,
    cohort: str,
    ece_text: str,
    brier_text: str,
    n_bins: int = 15,
) -> None:
    """Reliability diagram with predicted-probability distribution at bottom."""
    p_pos = np.asarray(p_pos, dtype=float)
    labels = np.asarray(labels, dtype=float)
    bins = np.linspace(0.0, 1.0, n_bins + 1)
    centers, accs, confs = [], [], []
    for i in range(n_bins):
        mask = (p_pos > bins[i]) & (p_pos <= bins[i + 1])
        centers.append((bins[i] + bins[i + 1]) / 2)
        if mask.sum() == 0:
            accs.append(np.nan)
            confs.append(np.nan)
            continue
        accs.append(labels[mask].mean())
        confs.append(p_pos[mask].mean())

    ax.plot([0, 1], [0, 1], "k--", lw=1)
    ax.bar(centers, accs, width=1 / n_bins * 0.9, alpha=0.6,
           color=COHORT_COLORS[cohort], edgecolor="k", linewidth=0.4,
           label="Observed frequency")
    ax.plot(centers, confs, "o", ms=3, color="#111111",
            label="Mean predicted probability")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Predicted probability")
    ax.set_ylabel("Observed frequency")

    ax2 = ax.twinx()
    ax2.hist(p_pos, bins=bins, histtype="stepfilled", alpha=0.18,
             color="gray", edgecolor="none")
    ax2.set_yticks([])
    ax2.set_ylim(0, len(p_pos) * 0.75)
    ax.text(0.03, 0.95, f"ECE {ece_text}  ·  Brier {brier_text}",
            transform=ax.transAxes, fontsize=8, va="top")


def fig_referral(
    ax,
    rates: Sequence[float],
    mc_error: Sequence[float],
    confidence_error: Sequence[float] | None,
    random_error: Sequence[float],
    cohort: str,
) -> None:
    """Referral-error trade-off curves (MC Dropout / plain confidence / random)."""
    rates = np.asarray(rates)
    ax.plot(rates, mc_error, "-", color=COLORS["mc"], lw=2, label="MC Dropout")
    if confidence_error is not None:
        ax.plot(rates, confidence_error, "-s", color=COLORS["confidence"],
                ms=4, lw=1.2, label="Plain confidence")
    ax.plot(rates, random_error, "--", color=COLORS["random"], lw=1.5,
            label="Random referral")
    ax.set_xlabel("Referral rate")
    ax.set_ylabel("Retained-case error rate")
    ax.set_xlim(0, 0.55)
    ax.set_ylim(0, max(np.nanmax(mc_error), 0.45))


def fig_risk_coverage(ax, coverage: Sequence[float], risk: Sequence[float], cohort: str) -> None:
    """Risk-coverage curve (confidence-based selective prediction)."""
    ax.plot(coverage, risk, lw=2, color=COHORT_COLORS[cohort],
            label=COHORT_LABELS[cohort])
    ax.set_xlabel("Coverage")
    ax.set_ylabel("Risk (error rate)")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, max(np.max(risk), 0.1))


def fig_subgroup(ax, report: dict[str, dict]) -> None:
    """RSNA subgroup bars: mean predicted probability by subgroup."""
    names = ["Lung Opacity", "No Lung Opacity / Not Normal", "Normal"]
    means = [report[n]["mean_prob"] for n in names]
    colors = ["#d62728", "#ff7f0e", "#2ca02c"]
    bars = ax.bar(names, means, color=colors, alpha=0.85, edgecolor="k", linewidth=0.5)
    ax.axhline(0.5, color="k", ls="--", lw=1)
    ax.set_ylim(0, 1)
    ax.set_ylabel("Mean predicted pneumonia probability")
    for bar, v in zip(bars, means):
        ax.text(bar.get_x() + bar.get_width() / 2, v + 0.02, f"{v:.2f}",
                ha="center", fontsize=9)


def fig_pipeline(ax) -> None:
    """Study-flow schematic (data -> split -> training -> uncertainty -> referral -> external)."""
    ax.axis("off")
    boxes = [
        ("Chest X-ray datasets\nKermany (5,856) / RSNA (26,684) / NIH (9,103)", 0.5, 0.94),
        ("Patient-level split\n70/15/15, seed 42", 0.5, 0.74),
        ("ResNet-18 training\n3 seeds, frozen backbone + layer4/head", 0.5, 0.54),
        ("MC Dropout uncertainty\n30 stochastic passes", 0.5, 0.34),
        ("Referral policy\nuncertain cases -> human review", 0.5, 0.14),
    ]
    for text, x, y in boxes:
        box = FancyBboxPatch((x - 0.33, y - 0.07), 0.66, 0.14,
                             boxstyle="round,pad=0.008", linewidth=1,
                             edgecolor="#333333", facecolor="#eef3f8")
        ax.add_patch(box)
        ax.text(x, y, text, ha="center", va="center", fontsize=8.5)
    for y_from, y_to in [(0.88, 0.81), (0.68, 0.61), (0.48, 0.41), (0.28, 0.21)]:
        ax.add_patch(FancyArrowPatch((0.5, y_from), (0.5, y_to),
                                     arrowstyle="-|>", mutation_scale=12,
                                     color="#333333"))
    ax.text(0.97, 0.03, "External validation: RSNA / NIH\n(no retraining, no threshold tuning)",
            ha="right", va="bottom", fontsize=8, style="italic")


def fig_domain_summary(ax_auc, ax_ece, table: list[dict]) -> None:
    """Domain-shift summary: AUC and ECE across cohorts."""
    names = ["internal_test", "rsna", "nih"]
    labels = [COHORT_LABELS[n] for n in names]
    aucs = [next(r["auc"] for r in table if r["dataset"] == n) for n in names]
    eces = [next(r["ece_raw"] for r in table if r["dataset"] == n) for n in names]

    bars = ax_auc.bar(labels, aucs, color=[COHORT_COLORS[n] for n in names],
                      alpha=0.85, edgecolor="k", linewidth=0.5)
    ax_auc.set_ylim(0, 1.1)
    ax_auc.set_ylabel("AUC")
    ax_auc.set_xticks(range(len(labels)))
    ax_auc.set_xticklabels(labels, rotation=15, ha="right", fontsize=8)
    for bar, v in zip(bars, aucs):
        ax_auc.text(bar.get_x() + bar.get_width() / 2, v + 0.02, f"{v:.3f}",
                    ha="center", fontsize=9)

    bars = ax_ece.bar(labels, eces, color=[COHORT_COLORS[n] for n in names],
                      alpha=0.85, edgecolor="k", linewidth=0.5)
    ax_ece.set_ylabel("ECE (raw)")
    ax_ece.set_xticks(range(len(labels)))
    ax_ece.set_xticklabels(labels, rotation=15, ha="right", fontsize=8)
    for bar, v in zip(bars, eces):
        ax_ece.text(bar.get_x() + bar.get_width() / 2, v + 0.01, f"{v:.3f}",
                    ha="center", fontsize=9)
